### ISSUE TITLE
Thoughts about how to download attachments?

### ISSUE THREAD

**Issue by simoneb** [j178/github-s3#1]
Thanks for this repo, it's quite disappointing that GitHub doesn't support this from the API.

I have read the code and what you're doing is quite smart. I assume that downloading attachments would be much simpler than uploading them, but I would like to hear from your experience building this what is the lifetime of the session cookie. 

Assuming that I want to build something that keeps running over time without having to provide credentials regularly, do you think the session cookie trick works, or would I have to come up with a smarter way to obtain one at intervals?

**Comment by j178** [comment]
Thanks. Downloading attachments, if the repository is public, no credentials should be required.

Concerning the session cookie’s lifespan, I’ve been using the same cookie for [a daily action](https://github.com/j178/j178/blob/master/.github/workflows/update.yaml) since August without issues - it appears to remain valid for several months at least.

**Comment by simoneb** [comment]
Yeah the repo is private, that's the issue. I noticed that you can access issues containing attachments with the API but then you'll get a 404 when trying to download attachments linked in the body of the issue, and then realized that this is not possible via API. Thanks for the details, I'll try this out
